In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [112]:
df = pd.read_csv('train.csv')


In [38]:
df.head(40)

PassengerId  Survived  Pclass  ...      Fare        Cabin  Embarked
0             1         0       3  ...    7.2500          NaN         S
1             2         1       1  ...   71.2833          C85         C
2             3         1       3  ...    7.9250          NaN         S
3             4         1       1  ...   53.1000         C123         S
4             5         0       3  ...    8.0500          NaN         S
5             6         0       3  ...    8.4583          NaN         Q
6             7         0       1  ...   51.8625          E46         S
7             8         0       3  ...   21.0750          NaN         S
8             9         1       3  ...   11.1333          NaN         S
9            10         1       2  ...   30.0708          NaN         C
10           11         1       3  ...   16.7000           G6         S
11           12         1       1  ...   26.5500         C103         S
12           13         0       3  ...    8.0500          NaN         S
13           14         0       3  ...   31.2750          NaN         S
14           15         0       3  ...    7.8542          NaN         S
15           16         1       2  ...   16.0000          NaN         S
16           17         0       3  ...   29.1250          NaN         Q
17           18         1       2  ...   13.0000          NaN         S
18           19         0       3  ...   18.0000          NaN         S
19           20         1       3  ...    7.2250          NaN         C
20           21         0       2  ...   26.0000          NaN         S
21           22         1       2  ...   13.0000          D56         S
22           23         1       3  ...    8.0292          NaN         Q
23           24         1       1  ...   35.5000           A6         S
24           25         0       3  ...   21.0750          NaN         S
25           26         1       3  ...   31.3875          NaN         S
26           27         0       3  ...    7.2250          NaN         C
27           28         0       1  ...  263.0000  C23 C25 C27         S
28           29         1       3  ...    7.8792          NaN         Q
29           30         0       3  ...    7.8958          NaN         S
30           31         0       1  ...   27.7208          NaN         C
31           32         1       1  ...  146.5208          B78         C
32           33         1       3  ...    7.7500          NaN         Q
33           34         0       2  ...   10.5000          NaN         S
34           35         0       1  ...   82.1708          NaN         C
35           36         0       1  ...   52.0000          NaN         S
36           37         1       3  ...    7.2292          NaN         C
37           38         0       3  ...    8.0500          NaN         S
38           39         0       3  ...   18.0000          NaN         S
39           40         1       3  ...   11.2417          NaN         C

[40 rows x 12 columns]

Data cleaning



________________________________________________________________________________

In [80]:
# Splitting the Name column into just the titles, in case there is a correlation
for i in range(len(df['Name'])):
  l = df.at[i,'Name'].split(', ')
  l1 = l[1].split('. ')
  df.at[i,'Name'] = l1[0]


In [5]:
df['Name'].head()

0      Mr
1     Mrs
2    Miss
3     Mrs
4      Mr
Name: Name, dtype: object

In [6]:
print(df['Name'].unique())

['Mr' 'Mrs' 'Miss' 'Master' 'Don' 'Rev' 'Dr' 'Mme' 'Ms' 'Major' 'Lady'
 'Sir' 'Mlle' 'Col' 'Capt' 'the Countess' 'Jonkheer']


In [40]:
y = df["Name"].values
from collections import Counter
Counter(y).most_common()

[('Mr', 517),
 ('Miss', 182),
 ('Mrs', 125),
 ('Master', 40),
 ('Dr', 7),
 ('Rev', 6),
 ('Major', 2),
 ('Mlle', 2),
 ('Col', 2),
 ('Don', 1),
 ('Mme', 1),
 ('Ms', 1),
 ('Lady', 1),
 ('Sir', 1),
 ('Capt', 1),
 ('the Countess', 1),
 ('Jonkheer', 1)]

In [8]:
df.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [41]:
print(df[df['Pclass'] == 1]['Age'].mean())
print(df[df['Pclass'] == 2]['Age'].mean())
print(df[df['Pclass'] == 3]['Age'].mean())

38.233440860215055
29.87763005780347
25.14061971830986


In [81]:
#Replacing null value ages with averages in each class
for i in range(len(df['Age'])):
  if pd.isnull(df.at[i,'Age']) == True:
    if df.at[i,'Pclass'] == 1:
      df.at[i,'Age'] = 38
    elif df.at[i,'Pclass'] == 2:
      df.at[i,'Age'] = 30
    elif df.at[i,'Pclass'] == 3:
      df.at[i,'Age'] = 25
   

In [43]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [44]:
df.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [46]:
#Most people weren't in cabins, but it's worth noting if they were or not
for i in range(len(df['Cabin'])):
  if pd.isnull(df.at[i,'Cabin']) == True:
    df.at[i,'Cabin'] = 0
  else:
    df.at[i,'Cabin'] = 1
print(df['Cabin'].unique())
   

[0 1]


In [47]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       2
dtype: int64

In [48]:
print(df['Embarked'].unique())

['S' 'C' 'Q' nan]


In [49]:
df.head()


PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500     0         S
1            2         1       1  ...  71.2833     1         C
2            3         1       3  ...   7.9250     0         S
3            4         1       1  ...  53.1000     1         S
4            5         0       3  ...   8.0500     0         S

[5 rows x 12 columns]

In [50]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [85]:
#Number of the ticket should be useless to the algorithm, same for passengerID
df.drop(['Ticket','PassengerId'],axis=1,inplace=True)

In [ ]:
df.head()

Survived  Pclass  Name  Sex   Age  SibSp  Parch     Fare  Cabin Embarked
0         0       3    11    1  22.0      1      0   7.2500      0        S
1         1       1    12    0  38.0      1      0  71.2833      1        C
2         1       3     8    0  26.0      0      0   7.9250      0        S
3         1       1    12    0  35.0      1      0  53.1000      1        S
4         0       3    11    1  35.0      0      0   8.0500      0        S

In [18]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [84]:
#Where the passengers embarked on the ship is also useless to what we're trying to achieve
df.drop('Embarked',axis=1,inplace=True)


In [53]:
from sklearn.preprocessing import LabelEncoder
encodings_dictionary = dict()
for c in df.columns:
    if df[c].dtype == "object":
        encodings_dictionary[c] = LabelEncoder()
        df[c] = encodings_dictionary[c].fit_transform(df[c])

In [54]:
df.head()

Survived  Pclass  Name  Sex   Age  SibSp  Parch     Fare  Cabin
0         0       3    11    1  22.0      1      0   7.2500      0
1         1       1    12    0  38.0      1      0  71.2833      1
2         1       3     8    0  26.0      0      0   7.9250      0
3         1       1    12    0  35.0      1      0  53.1000      1
4         0       3    11    1  35.0      0      0   8.0500      0

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Name      891 non-null    int64  
 3   Sex       891 non-null    int64  
 4   Age       891 non-null    float64
 5   SibSp     891 non-null    int64  
 6   Parch     891 non-null    int64  
 7   Fare      891 non-null    float64
 8   Cabin     891 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 62.8 KB


Data Preprocessing


________________________________________________________________________________

In [97]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X = df.drop('Survived',axis=1)
y= df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


Checking a few models

________________________________________________________________________________

In [56]:
from sklearn.svm import SVC

svm=SVC()
svm.fit(X_train, y_train)
predictions = svm.predict(X_test)

In [57]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

           0       0.87      0.88      0.87       112
           1       0.79      0.78      0.78        67

    accuracy                           0.84       179
   macro avg       0.83      0.83      0.83       179
weighted avg       0.84      0.84      0.84       179

[[98 14]
 [15 52]]


In [58]:
from sklearn.model_selection import GridSearchCV

param_grid = {'C':[0.5,1,10,100,1000], 'gamma':[0.1,0.01,0.001,0.0001,0.00001]}

grid = GridSearchCV(SVC(), param_grid, refit=True, verbose=True)

grid.fit(X_train,y_train)
grid_predictions = grid.predict(X_test)
print(classification_report(y_test,grid_predictions))
print(confusion_matrix(y_test,grid_predictions))

Fitting 5 folds for each of 25 candidates, totalling 125 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


              precision    recall  f1-score   support

           0       0.87      0.88      0.87       112
           1       0.79      0.78      0.78        67

    accuracy                           0.84       179
   macro avg       0.83      0.83      0.83       179
weighted avg       0.84      0.84      0.84       179

[[98 14]
 [15 52]]


[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed:    3.0s finished


In [59]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr_predictions = lr.predict(X_test)
print(classification_report(y_test,lr_predictions))
print(confusion_matrix(y_test,lr_predictions))

              precision    recall  f1-score   support

           0       0.84      0.86      0.85       112
           1       0.75      0.73      0.74        67

    accuracy                           0.81       179
   macro avg       0.80      0.79      0.80       179
weighted avg       0.81      0.81      0.81       179

[[96 16]
 [18 49]]


In [60]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knn_predictions = knn.predict(X_test)
print(classification_report(y_test,knn_predictions))
print(confusion_matrix(y_test,knn_predictions))

              precision    recall  f1-score   support

           0       0.88      0.82      0.85       112
           1       0.73      0.81      0.77        67

    accuracy                           0.82       179
   macro avg       0.80      0.81      0.81       179
weighted avg       0.82      0.82      0.82       179

[[92 20]
 [13 54]]


In [61]:
from sklearn.feature_selection import RFECV
from sklearn.ensemble import RandomForestClassifier
m = RFECV(RandomForestClassifier(), scoring='accuracy')
m.fit(X_train, y_train)
m_predictions = m.predict(X_test)
print(classification_report(y_test,m_predictions))
print(confusion_matrix(y_test,m_predictions))

              precision    recall  f1-score   support

           0       0.86      0.85      0.86       112
           1       0.75      0.78      0.76        67

    accuracy                           0.82       179
   macro avg       0.81      0.81      0.81       179
weighted avg       0.82      0.82      0.82       179

[[95 17]
 [15 52]]


In [100]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf_predictions = rf.predict(X_test)
print(classification_report(y_test,rf_predictions))
print(confusion_matrix(y_test,rf_predictions))

              precision    recall  f1-score   support

           0       0.88      0.86      0.87       111
           1       0.77      0.81      0.79        68

    accuracy                           0.84       179
   macro avg       0.83      0.83      0.83       179
weighted avg       0.84      0.84      0.84       179

[[95 16]
 [13 55]]


PCA, to check if some columns confuse the algorithm

In [31]:
from sklearn.decomposition import PCA
pca = PCA(.99)
pca.fit(X_train)

PCA(copy=True, iterated_power='auto', n_components=0.99, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [33]:
pca.n_components_

8

TPOT

In [34]:
pip install tpot

     |████████████████████████████████| 87 kB 2.3 MB/s 
     |████████████████████████████████| 160 kB 18.7 MB/s 
     |████████████████████████████████| 173.5 MB 63 kB/s 
  Created wheel for stopit: filename=stopit-1.1.2-py3-none-any.whl size=11952 sha256=230876a9fcb6a685452aa100725fe7e89539219b1978a74a6e392d893a9a760f
  Stored in directory: /root/.cache/pip/wheels/e2/d2/79/eaf81edb391e27c87f51b8ef901ecc85a5363dc96b8b8d71e3
Successfully built stopit
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90


In [35]:
from tpot import TPOTClassifier
tpot = TPOTClassifier(max_time_mins=30, verbosity=2)
tpot.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]


Generation 1 - Current best internal CV score: 0.818831872352999

Generation 2 - Current best internal CV score: 0.818831872352999

Generation 3 - Current best internal CV score: 0.818831872352999

Generation 4 - Current best internal CV score: 0.818831872352999

Generation 5 - Current best internal CV score: 0.8287501231163203


TPOT closed during evaluation in one generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: KNeighborsClassifier(XGBClassifier(input_matrix, learning_rate=1.0, max_depth=8, min_child_weight=4, n_estimators=100, n_jobs=1, subsample=0.55, verbosity=0), n_neighbors=82, p=1, weights=uniform)

Best pipeline: KNeighborsClassifier(XGBClassifier(input_matrix, learning_rate=1.0, max_depth=8, min_child_weight=4, n_estimators=100, n_jobs=1, subsample=0.55, verbosity=0), n_neighbors=82, p=1, weights=uniform)


TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
               disable_update_check=False, early_stop=None, generations=100,
               log_file=None, max_eval_time_mins=5, max_time_mins=30,
               memory=None, mutation_rate=0.9, n_jobs=1, offspring_size=None,
               periodic_checkpoint_folder=None, population_size=100,
               random_state=None, scoring=None, subsample=1.0, template=None,
               use_dask=False, verbosity=2, warm_start=False)

In [36]:
tpot_predictions = tpot.predict(X_test)
print(classification_report(y_test,tpot_predictions))
print(confusion_matrix(y_test,tpot_predictions))
#For 30 minutes of fitting, the best solution is:
# XGBClassifier(input_matrix, learning_rate=0.1, max_depth=5, min_child_weight=4, n_estimators=100, n_jobs=1, subsample=0.9500000000000001, verbosity=0

              precision    recall  f1-score   support

           0       0.86      0.89      0.88       120
           1       0.76      0.71      0.74        59

    accuracy                           0.83       179
   macro avg       0.81      0.80      0.81       179
weighted avg       0.83      0.83      0.83       179

[[107  13]
 [ 17  42]]
